/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AuthRequest {
  /**
   * Username of user logging in
   */
  username: string;
  /**
   * Password of user logging in in plaintext
   */
  password: string;
  /**
   * If your client supports moods, send this key with a value of the highest mood ID you have cached/stored on the user's computer. For example, if you logged in last time with and got mood IDs 1, 2, 4, and 5, then send '5' as the value. The server will return every new mood that has an internal MoodID greater than 5. If you've never downloaded moods before, send '0'. If you don't care about getting any moods at all (if your client doesn't support them), then don't send this key at all.
   */
  last_mood_id?: number;
  /**
   * If your client supports picture keywords and you want to receive that list, set this to true, and you'll receive the list of picture keywords the user has defined.
   */
  get_picture_keywords?: boolean;
  /**
   * If your client supports picture keywords and can also display the pictures somehow, set this to true, and you'll receive the list of picture keyword URLs that correspond to the picture keywords as well as the URL for the default picture. You must send 'get_picture_keywords' for this option to even matter.
   */
  get_picture_urls?: boolean;
  [k: string]: any;
}
