/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FriendsCheckResponse {
  /**
   * True if there are new items
   */
  new?: boolean;
  /**
   * How many seconds you must wait before polling the server again
   */
  interval?: number;
  /**
   * The number of items that are contained in this response (numbered started at 1)
   */
  count?: number;
  /**
   * The total number of items that have been updated since the time specified
   */
  total?: number;
  /**
   * Error message(s), if failed
   */
  errors?: string[];
  [k: string]: any;
}
