/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface FriendGroup {
  /**
   * The bit number of this friend group, from 1-30
   */
  id: number;
  /**
   * Name of this friend group
   */
  name: string;
  /**
   * The sort order of this friend group, from 0-255
   */
  sortorder: number;
  /**
   * If this friend group is public
   */
  public: boolean;
  [k: string]: any;
}
